#!/usr/bin/env python3
"""Builds the GitHub Issue markdown body for the weekly doc drift report."""

import argparse
from datetime import datetime

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--gaps-file", required=True)
    parser.add_argument("--since", required=True)
    parser.add_argument("--date", required=True)
    args = parser.parse_args()

    with open(args.gaps_file) as f:
        lines = [l.strip() for l in f.readlines() if l.strip()]

    # Last line is the count sentinel written by the audit script
    gaps = [l for l in lines if "|" in l]

    if not gaps:
        print("No gaps found.")
        return

    rows = []
    for line in gaps:
        parts = line.split("|", 2)
        if len(parts) == 3:
            sha, msg, docs_csv = parts
            doc_list = " ".join(f"`{d}`" for d in docs_csv.split(",") if d)
            rows.append((sha, msg, doc_list))

    body = f"""## 📋 Doc Drift Report — week of {args.date}

**{len(rows)} commit(s) may need documentation updates.**

| Commit | Message | Suggested Docs to Check |
|--------|---------|--------------------------|
"""
    for sha, msg, doc_list in rows:
        body += f"| `{sha}` | {msg} | {doc_list} |\n"

    body += """
### How to action this
1. Review each commit (`git show <sha>`)
2. Check the suggested doc — does it accurately describe the current behaviour?
3. Update the doc if needed, commit with `docs(scope): ...`
4. Close this issue or label `doc-drift-false-positive` if no update is needed

### Escape hatch
To suppress future flagging for a specific commit, add `[no-doc]` to the commit message,
or use a `chore:`/`docs:`/`test:` prefix.

_Auto-generated by [doc-drift-auditor](../../actions/workflows/doc-drift-auditor.yml) ·
mapping rules: [`.github/doc-drift-mappings.yml`](../../blob/main/.github/doc-drift-mappings.yml)_
"""
    print(body)

if __name__ == "__main__":
    main()
