services:
  redis:
    image: redis:7.2-alpine
    container_name: batbern-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - batbern-network

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile.dev
    container_name: batbern-api-gateway
    ports:
      - "${API_GATEWAY_PORT:-8080}:8080"
    working_dir: /workspace
    environment:
      # Spring Configuration
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-local}
      - LOG_LEVEL=${LOG_LEVEL:-DEBUG}

      # AWS Configuration
      - AWS_REGION=${AWS_REGION:-eu-central-1}

      # Database Configuration (AWS RDS)
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT:-5432}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DATABASE_URL=${DATABASE_URL}

      # Redis Configuration (Local Container)
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}

      # Cognito Configuration (AWS)
      - COGNITO_USER_POOL_ID=${COGNITO_USER_POOL_ID}
      - COGNITO_CLIENT_ID=${COGNITO_CLIENT_ID}

      # Feature Flags
      - ENABLE_COGNITO_AUTH=${ENABLE_COGNITO_AUTH:-true}
    volumes:
      - .:/workspace
      - gradle-cache:/root/.gradle
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - batbern-network

  web-frontend:
    build:
      context: ./web-frontend
      dockerfile: Dockerfile.dev
    container_name: batbern-frontend
    ports:
      - "3000:3000"
    environment:
      # API Configuration
      - VITE_API_BASE_URL=${VITE_API_BASE_URL:-http://localhost:8080}

      # AWS Configuration
      - VITE_AWS_REGION=${VITE_AWS_REGION:-eu-central-1}

      # Cognito Configuration (AWS)
      - VITE_COGNITO_USER_POOL_ID=${VITE_COGNITO_USER_POOL_ID}
      - VITE_COGNITO_CLIENT_ID=${VITE_COGNITO_CLIENT_ID}
    volumes:
      - ./web-frontend:/app
      - /app/node_modules
    depends_on:
      api-gateway:
        condition: service_healthy
    networks:
      - batbern-network

volumes:
  redis-data:
    driver: local
  gradle-cache:
    driver: local

networks:
  batbern-network:
    driver: bridge
