spring:
  application:
    name: api-gateway
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

# AWS Cognito Configuration
aws:
  cognito:
    userPoolId: ${COGNITO_USER_POOL_ID}
    region: ${AWS_REGION:eu-central-1}
    appClientId: ${COGNITO_CLIENT_ID}

logging:
  level:
    ch.batbern: DEBUG
    org.springframework: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] [%X{correlationId}] %-5level %logger{36} - %msg%n"

# Error handling configuration
server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param  # Only in dev/staging via profile
    include-exception: false      # Never expose internal exception classes
