server:
  port: 8080
  compression:
    enabled: false

spring:
  application:
    name: attendee-experience-service

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
