package ch.batbern.gateway.auth;

import ch.batbern.gateway.auth.model.UserContext;
import com.auth0.jwt.interfaces.DecodedJWT;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Component;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

@Slf4j
@Component
@RequiredArgsConstructor
public class UserContextExtractor {

    private final ObjectMapper objectMapper;

    public UserContext extractUserContext(DecodedJWT jwt) {
        UserContext.UserContextBuilder builder = UserContext.builder()
                .userId(jwt.getSubject())
                .sessionId(jwt.getId());

        // Extract username (Story 1.16.2: Public meaningful username identifier)
        // Prefer custom:username (from database) over cognito:username (UUID auto-generated by Cognito)
        // PreTokenGeneration Lambda sets custom:username from database user_profiles.username
        String username = null;
        if (jwt.getClaim("custom:username") != null && !jwt.getClaim("custom:username").isNull()) {
            username = jwt.getClaim("custom:username").asString();
        }
        if (username != null) {
            builder.username(username);
        }

        // Extract standard claims
        if (jwt.getClaim("email") != null && !jwt.getClaim("email").isNull()) {
            builder.email(jwt.getClaim("email").asString());
        }

        if (jwt.getClaim("email_verified") != null && !jwt.getClaim("email_verified").isNull()) {
            Boolean emailVerified = jwt.getClaim("email_verified").asBoolean();
            builder.emailVerified(emailVerified != null ? emailVerified : false); 
        } else {
            builder.emailVerified(false);
        }

        // Extract role from custom:role claim (Story 1.2.6: ADR-001 migration)
        // Format: comma-separated string from DB (e.g., "ORGANIZER,SPEAKER")
        // Convert to lowercase for consistency with application layer
        // First role is primary, remaining roles are additional roles
        if (jwt.getClaim("custom:role") != null && !jwt.getClaim("custom:role").isNull()) {
            try {
                String rolesString = jwt.getClaim("custom:role").asString();
                if (rolesString != null && !rolesString.isEmpty()) {
                    String[] roles = rolesString.split(",");
                    if (roles.length > 0) {
                        // Set primary role (first in list, converted to lowercase)
                        builder.role(roles[0].trim().toLowerCase());

                        // Set additional roles (if any, converted to lowercase)
                        if (roles.length > 1) {
                            List<String> additionalRoles = new ArrayList<>();
                            for (int i = 1; i < roles.length; i++) {
                                additionalRoles.add(roles[i].trim().toLowerCase());
                            }
                            builder.additionalRoles(additionalRoles);
                        }
                    }
                }
            } catch (Exception e) {
                log.warn("Failed to extract custom:role: {}", e.getMessage());
            }
        }

        if (jwt.getClaim("custom:companyId") != null && !jwt.getClaim("custom:companyId").isNull()) {
            builder.companyId(jwt.getClaim("custom:companyId").asString());
        }

        // Extract preferences as JSON
        Map<String, Object> preferences = extractPreferences(jwt);
        builder.preferences(preferences);

        // Extract token metadata
        if (jwt.getIssuedAt() != null) {
            builder.issuedAt(jwt.getIssuedAt().toInstant());
        }

        if (jwt.getExpiresAt() != null) {
            builder.expiresAt(jwt.getExpiresAt().toInstant());
        }

        return builder.build();
    }

    private Map<String, Object> extractPreferences(DecodedJWT jwt) {
        if (jwt.getClaim("custom:preferences") == null || jwt.getClaim("custom:preferences").isNull()) {
            return new HashMap<>();
        }

        String preferencesJson = jwt.getClaim("custom:preferences").asString();
        if (preferencesJson == null || preferencesJson.isEmpty()) {
            return new HashMap<>();
        }

        try {
            return objectMapper.readValue(preferencesJson, new TypeReference<Map<String, Object>>() {});
        } catch (Exception e) {
            log.warn("Failed to parse preferences JSON: {}", e.getMessage());
            return new HashMap<>();
        }
    }
}