import { defineConfig, devices } from '@playwright/test';

/**
 * Playwright E2E Test Configuration
 *
 * Environment-aware configuration enables testing against different environments:
 * - development: Local Docker environment (localhost:3000)
 * - staging: AWS staging environment (staging.batbern.ch)
 * - production: AWS production environment (batbern.ch)
 *
 * Usage:
 *   npm run test:e2e              # Regular E2E tests (excludes documentation tests)
 *   npm run test:e2e:staging      # Test staging
 *   npm run test:e2e:production   # Test production
 *   npm run test:e2e:docs         # Documentation screenshot/video tests (opt-in only)
 *
 * Documentation Tests:
 *   By default, documentation screenshot and screencast tests are EXCLUDED because they:
 *   - Take 10-60 minutes to run (full workflow from event creation to archival)
 *   - Generate documentation artifacts (screenshots/videos), not validate functionality
 *   - Should only run when explicitly generating documentation
 *
 *   To run them: INCLUDE_DOCS_TESTS=true npm run test:e2e
 */

// Get test environment from environment variable
const testEnv = process.env.TEST_ENV || 'development';

// Environment-specific configuration
const envConfig = {
  development: {
    baseURL: 'http://localhost:8100',
    apiURL: 'http://localhost:8000',
  },
  staging: {
    baseURL: 'https://staging.batbern.ch',
    apiURL: 'https://api.staging.batbern.ch',
  },
  production: {
    baseURL: 'https://batbern.ch',
    apiURL: 'https://api.batbern.ch',
  },
}[testEnv as 'development' | 'staging' | 'production'];

if (!envConfig) {
  throw new Error(`Invalid TEST_ENV: ${testEnv}. Must be one of: development, staging, production`);
}

console.log(`Running Playwright tests against: ${testEnv} (${envConfig.baseURL})`);

// Export config for use in test files
export const BASE_URL = envConfig.baseURL;
export const API_URL = envConfig.apiURL;
export const TEST_ENV = testEnv;

export default defineConfig({
  testDir: './e2e',

  /* Global setup to handle authentication */
  globalSetup: './e2e/global-setup.ts',

  /* Run tests in files in parallel */
  fullyParallel: true,

  /* Fail the build on CI if you accidentally left test.only in the source code. */
  forbidOnly: !!process.env.CI,

  /* Retry on CI only */
  retries: process.env.CI ? 2 : 0,

  /* Opt out of parallel tests on CI. */
  workers: process.env.CI ? 1 : undefined,

  /* Reporter to use. See https://playwright.dev/docs/test-reporters */
  reporter: [['html'], ['junit', { outputFile: 'test-results/junit.xml' }], ['list']],

  /* Shared settings for all the projects below. See https://playwright.dev/docs/api/class-testoptions. */
  use: {
    /* Base URL for the environment being tested */
    baseURL: envConfig.baseURL,

    /* Use saved authenticated state - generated by global-setup.ts */
    storageState: '.playwright-auth-state.json',

    /* Set browser locale to English for E2E tests */
    locale: 'en-US',

    /* Collect trace when retrying the failed test. See https://playwright.dev/docs/trace-viewer */
    trace: 'on-first-retry',

    /* Screenshot on failure */
    screenshot: 'only-on-failure',

    /* Video on failure */
    video: 'retain-on-failure',

    /* Extra HTTP headers for all requests */
    extraHTTPHeaders: {
      'X-Test-Environment': testEnv,
      'Accept-Language': 'en-US,en;q=0.9',
      ...(process.env.AUTH_TOKEN ? { Authorization: `Bearer ${process.env.AUTH_TOKEN}` } : {}),
    },
  },

  /* Configure projects for major browsers */
  projects: [
    // ── ORGANIZER (default) ──────────────────────────────────────────────────
    // Runs all tests not claimed by role-specific projects.
    // Uses .playwright-auth-state.json (organizer token — legacy path).
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
      testIgnore: [
        // Exclude role-specific test directories (handled by partner/speaker projects)
        '**/e2e/partner/**',
        '**/e2e/speaker/**',
        // Exclude documentation tests unless opted-in
        ...(process.env.INCLUDE_DOCS_TESTS
          ? []
          : [
              '**/workflows/documentation/**',
              '**/screencast-event-workflow.spec.ts',
              '**/verify-timing.spec.ts',
            ]),
      ],
    },

    // ── SPEAKER (optional) ───────────────────────────────────────────────────
    // Runs tests in e2e/speaker/ as an authenticated speaker user.
    // Only activated when SPEAKER_AUTH_TOKEN env var is set (set by run-playwright-tests.sh
    // or when the ~/.batbern/{env}-speaker.json token file exists).
    ...(process.env.SPEAKER_AUTH_TOKEN
      ? [
          {
            name: 'speaker',
            use: {
              ...devices['Desktop Chrome'],
              storageState: '.playwright-auth-speaker.json',
            },
            testMatch: '**/e2e/speaker/**/*.spec.ts',
          },
        ]
      : []),

    // ── PARTNER (optional) ───────────────────────────────────────────────────
    // Runs tests in e2e/partner/ as an authenticated partner user.
    // Only activated when PARTNER_AUTH_TOKEN env var is set.
    ...(process.env.PARTNER_AUTH_TOKEN
      ? [
          {
            name: 'partner',
            use: {
              ...devices['Desktop Chrome'],
              storageState: '.playwright-auth-partner.json',
            },
            testMatch: '**/e2e/partner/**/*.spec.ts',
          },
        ]
      : []),
    // {
    //   name: 'Mobile Safari',
    //   use: { ...devices['iPhone 17'] },
    // },

    // Additional browsers (only run with explicit --project flag)
    // Uncomment to enable by default
    // {
    //   name: 'firefox',
    //   use: { ...devices['Desktop Firefox'] },
    // },
    // {
    //   name: 'webkit',
    //   use: { ...devices['Desktop Safari'] },
    // },
    // {
    //   name: 'Mobile Chrome',
    //   use: { ...devices['Pixel 5'] },
    // },

    /* Documentation screenshots project - ONLY runs when INCLUDE_DOCS_TESTS=true */
    ...(process.env.INCLUDE_DOCS_TESTS
      ? [
          {
            name: 'documentation-screenshots',
            use: {
              // Don't spread devices preset - define all properties manually to avoid deviceScaleFactor issues
              browserName: 'chromium' as const,
              viewport: { width: 1920, height: 1080 }, // Full HD - proper scale for enterprise app
              deviceScaleFactor: 1, // CRITICAL: Prevent zoomed/distorted screenshots (must be 1)
              isMobile: false,
              hasTouch: false,
              video: 'retain-on-failure' as const,
              screenshot: 'only-on-failure' as const,
              // Ensure storage state is loaded for authenticated tests
              storageState: '.playwright-auth-state.json',
            },
            testMatch: /workflows\/documentation\/.*.spec.ts/, // Only run documentation tests
            retries: 0, // No retries - fail fast for debugging
          },

          /* Screencast training video project - Continuous recording for German training video */
          {
            name: 'screencast-training',
            use: {
              browserName: 'chromium' as const,
              viewport: { width: 1920, height: 1080 }, // Full HD viewport
              deviceScaleFactor: 1, // No zoom distortion
              isMobile: false,
              hasTouch: false,
              video: {
                mode: 'on' as const, // ALWAYS record video for screencast
                size: { width: 1920, height: 1080 }, // Full HD video recording (matches viewport)
              },
              screenshot: 'off' as const, // No screenshots needed (video only)
              storageState: '.playwright-auth-state.json',
              launchOptions: {
                slowMo: 500, // Slow down actions for clarity in video
                args: [
                  '--window-size=1920,1080', // Force window size
                  '--force-device-scale-factor=1', // Prevent DPI scaling
                ],
              },
            },
            testMatch: /screencast-event-workflow.spec.ts/, // Only run screencast test
            retries: 0, // No retries - want one clean recording
          },
        ]
      : []),
  ],

  /* Run your local dev server before starting the tests (development only) */
  webServer:
    testEnv === 'development'
      ? {
          command: 'make dev-native-up',
          url: 'http://localhost:8100',
          reuseExistingServer: !process.env.CI,
          timeout: 120 * 1000,
        }
      : undefined,
});
