server:
  port: 8080
  compression:
    enabled: false

spring:
  application:
    name: event-management-service
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    out-of-order: false
    validate-on-migrate: false
    clean-disabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
