/**
 * Timing Helper for Screencast / Narration Synchronization (v2 — duration-driven)
 *
 * v1 synchronized the test against a single pre-recorded audio file using hand-maintained
 * cumulative delays (timing-config.ts). v2 inverts the model: the VIDEO drives, the audio
 * follows. Each narration segment is a separate MP3 generated by
 * scripts/generate-narration-audio.mjs, whose measured duration is read from
 * narration-timings-{lang}.json. During the test:
 *
 *   logNarration(marker)      → records the segment's actual start offset (timeline)
 *   ...UI actions run while the narration "plays"...
 *   waitForNarration(marker)  → waits until startOffset + measured duration (+ gap)
 *
 * After the run, flushTimeline() writes narration-timeline-{lang}.json with the actual
 * start offsets — scripts/assemble-narration.mjs places each segment MP3 at exactly that
 * offset to produce a perfectly synchronized audio track + SRT. No manual timing files.
 *
 * Usage:
 *   import { assertNarrationTimings, startTimer, logNarration, waitForNarration, flushTimeline }
 *     from './screencast/timing-helper';
 *
 *   test.beforeAll(() => assertNarrationTimings());
 *   // in the test: startTimer(); logNarration('NARRATION_01', '...'); ...; await waitForNarration('NARRATION_01', page);
 *   test.afterAll(() => flushTimeline());
 */

import fs from 'node:fs';
import path from 'node:path';
import { Page } from '@playwright/test';

/** Language of the narration manifest/timings — switch via SCREENCAST_LANG (default: de). */
export const SCREENCAST_LANG = process.env.SCREENCAST_LANG ?? 'de';

/** Breathing gap appended after each segment before the next action (ms). */
const NARRATION_GAP_MS = Number(process.env.SCREENCAST_NARRATION_GAP_MS ?? 700);

/** Resolved from CWD because Playwright tests always run from web-frontend/. */
const SCREENCAST_DIR = path.resolve(process.cwd(), 'e2e/workflows/documentation/screencast');

interface NarrationTimingSegment {
  marker: string;
  file: string;
  durationMs: number;
  textHash: string;
}

interface NarrationTimings {
  lang: string;
  voiceId: string;
  modelId: string;
  fake: boolean;
  generatedAt: string;
  segments: NarrationTimingSegment[];
}

interface TimelineEntry {
  marker: string;
  startMs: number;
  durationMs: number;
}

let timings: NarrationTimings | null = null;
let scriptStartTime: number | null = null;
const timeline: TimelineEntry[] = [];

function timingsPath(): string {
  return path.join(SCREENCAST_DIR, `narration-timings-${SCREENCAST_LANG}.json`);
}

function loadTimings(): NarrationTimings {
  if (!timings) {
    const file = timingsPath();
    if (!fs.existsSync(file)) {
      throw new Error(
        `Narration timings not found: ${file}\n` +
          `Run "npm run screencast:narration" (or "npm run screencast:narration -- --fake" ` +
          `without ElevenLabs API access) before recording the screencast.`
      );
    }
    timings = JSON.parse(fs.readFileSync(file, 'utf8')) as NarrationTimings;
  }
  return timings;
}

function getSegment(marker: string): NarrationTimingSegment {
  const segment = loadTimings().segments.find((s) => s.marker === marker);
  if (!segment) {
    throw new Error(
      `No narration timing for marker "${marker}" — regenerate with "npm run screencast:narration"`
    );
  }
  return segment;
}

/**
 * Fail fast (in beforeAll) when the timings file is missing or stale.
 * Logs a loud warning when the timings were generated in --fake mode.
 */
export function assertNarrationTimings(): void {
  const loaded = loadTimings();
  if (loaded.fake) {
    console.warn(
      '⚠️  Narration timings were generated with --fake (silent placeholder audio).\n' +
        '   Fine for a dry run — regenerate with a real ElevenLabs voice before the final recording.'
    );
  }
  const totalSec = loaded.segments.reduce((sum, s) => sum + s.durationMs, 0) / 1000;
  console.log(
    `🎙  Narration timings loaded (${loaded.lang}, ${loaded.segments.length} segments, ` +
      `${totalSec.toFixed(1)}s total, voice=${loaded.voiceId}, model=${loaded.modelId})`
  );
}

/** Start the global timer. Call once, as close to the start of video recording as possible. */
export function startTimer(): void {
  scriptStartTime = Date.now();
  timeline.length = 0;
  console.log('🎬 Narration timer started');
}

/**
 * Mark the start of a narration segment: records the actual start offset into the timeline.
 * Call this right BEFORE performing the UI actions the narration describes.
 */
export function logNarration(marker: string, message: string): void {
  const segment = getSegment(marker);
  if (scriptStartTime === null) {
    console.warn(`⚠️  logNarration(${marker}) before startTimer() — offset recorded as 0`);
  }
  const startMs = scriptStartTime === null ? 0 : Date.now() - scriptStartTime;
  timeline.push({ marker, startMs, durationMs: segment.durationMs });
  console.log(`[${marker}] @${(startMs / 1000).toFixed(1)}s ${message}`);
}

/**
 * Wait until the narration segment has finished playing (start offset + measured duration
 * + breathing gap). If the UI actions already took longer, returns immediately.
 */
export async function waitForNarration(marker: string, page: Page): Promise<void> {
  const segment = getSegment(marker);
  const entry = timeline.find((t) => t.marker === marker);
  if (!entry || scriptStartTime === null) {
    console.warn(`⚠️  waitForNarration(${marker}) without logNarration/startTimer — fixed wait`);
    await page.waitForTimeout(segment.durationMs + NARRATION_GAP_MS);
    return;
  }

  const targetEnd = entry.startMs + segment.durationMs + NARRATION_GAP_MS;
  const elapsed = Date.now() - scriptStartTime;
  const timeToWait = Math.max(0, targetEnd - elapsed);

  console.log(
    `⏱️  [${marker}] start: ${(entry.startMs / 1000).toFixed(1)}s | ` +
      `audio: ${(segment.durationMs / 1000).toFixed(1)}s | wait: ${(timeToWait / 1000).toFixed(1)}s`
  );
  if (timeToWait > 0) {
    await page.waitForTimeout(timeToWait);
  } else {
    console.log('    ✓ UI actions outlasted the narration, continuing immediately');
  }
}

/**
 * Spread loop iterations across the narration window so the on-screen actions track the
 * voice instead of bunching at the segment start and leaving a static tail.
 *
 * Call at the TOP of iteration `index` (0-based) of `total` iterations inside a segment:
 * waits until the narration has reached roughly `index/total` of its duration (front 85%,
 * leaving the tail for the last action to finish). No-ops when the UI is already behind
 * schedule, so it can never extend a segment that is UI-bound.
 */
export async function paceWithinNarration(
  marker: string,
  index: number,
  total: number,
  page: Page
): Promise<void> {
  if (index <= 0 || total <= 1) return;
  const segment = getSegment(marker);
  const entry = timeline.find((t) => t.marker === marker);
  if (!entry || scriptStartTime === null) return;

  const targetOffset = entry.startMs + (segment.durationMs * 0.85 * index) / total;
  const wait = targetOffset - (Date.now() - scriptStartTime);
  if (wait > 0) {
    console.log(`    ⏸  pacing ${marker} item ${index + 1}/${total}: ${(wait / 1000).toFixed(1)}s`);
    await page.waitForTimeout(wait);
  }
}

/**
 * Write the recorded timeline to narration-timeline-{lang}.json.
 * Call from afterAll so it is flushed even when the test fails mid-run.
 */
export function flushTimeline(): void {
  if (timeline.length === 0) {
    console.warn('⚠️  flushTimeline(): empty timeline — nothing written');
    return;
  }
  const outPath = path.join(SCREENCAST_DIR, `narration-timeline-${SCREENCAST_LANG}.json`);
  const payload = {
    lang: SCREENCAST_LANG,
    recordedAt: new Date().toISOString(),
    segments: timeline,
  };
  fs.writeFileSync(outPath, JSON.stringify(payload, null, 2) + '\n');
  console.log(`🗒  Narration timeline written: ${outPath} (${timeline.length} segments)`);
}
