spring:
  datasource:
    # PostgreSQL via Testcontainers (configured dynamically in AbstractIntegrationTest)
    # Database connection properties are injected by @DynamicPropertySource
    driver-class-name: org.postgresql.Driver

  jpa:
    # Let Flyway manage schema - validate only
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  flyway:
    # Enable Flyway migrations for production parity
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  cache:
    type: caffeine
    caffeine:
      spec: expireAfterWrite=15m,maximumSize=1000

logging:
  level:
    ch.batbern: DEBUG
    org.springframework.cache: DEBUG
    org.testcontainers: INFO
    com.github.dockerjava: WARN
