server:
  port: 8080

spring:
  application:
    name: partner-coordination-service

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
